- name: install redis
  hosts: redis
  become: yes
  tasks:
  - name: install remi release
    ansible.bultin.dnf:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
      state: present
      disable_gpg_check: true

  - name: enable redis
    ansible.bultin.command: dnf module enable redis:remi-6.2 -y

  - name: install redis
    ansible.bultin.dnf: 
      name: redis -y
      state: present

  - name: allow remote conncections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes